Module: LambdaSharpChallenge.PollyToS3Module
Version: 1.0-DEV
Description: Send text to Polly to save an audio file to S3
Items:
  
  - Resource: PollyPermissions
    Scope: PollyFunction
    Value: "*"
    Allow:
      - polly:DescribeVoices
      - polly:SynthesizeSpeech

  - Resource: ArticlesBucket
    Scope: PollyFunction
    Type: AWS::S3::Bucket
    Allow: ReadWrite

  - Function: PollyFunction
    Description: Endpoints to send text to Polly to save to a S3 bucket
    Memory: 512
    Timeout: 30
    Sources:
      - Api: POST:/articles
        Invoke: Logic::AddItem

  - Resource: ArticleBucketPolicy
    Description: Public access policy for Articles bucket
    Type: AWS::S3::BucketPolicy
    Properties:
      # Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-policy.html
      Bucket: !Ref ArticlesBucket
      PolicyDocument: 
        Id: ArticlesBucket
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub "${ArticlesBucket.Arn}/*"

  - Resource: ArticleAudioDone
    Description: Send message once audio is ready
    Type: AWS::SNS::Topic
    Allow: Publish
    Scope: all
    Properties:
      # Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sns-topic.html
      Subscription:
        - Endpoint: 
          Protocol: SMS
      TopicName: AudioDone
